name: Addon Checks

on: [push]

jobs:
  # run flake8 but ignore long lines and whitespace after keyword
  flake8-lint:
    runs-on: ubuntu-latest
    name: flake8 Linter
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "E501,E275"
          exclude: "croniter.py"
  kodi-addon-checker:
    runs-on: ubuntu-latest
    name: Kodi addon checker
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Kodi addon checker validation
      id: kodi-addon-checker
      uses: xbmc/action-kodi-addon-checker@v1.2
      with:
        kodi-version: matrix
        is-pr: false
